import React, { useState } from 'react';
import { ArrowRight, CalendarDays, Check, Home, MessageSquare } from 'lucide-react';
import { SERVICES_LIST } from '../data/cleaningData';

export default function BookingCalculator({ onOpenBooking, initialSettings }) {
  const [serviceType, setServiceType] = useState(initialSettings?.serviceType || SERVICES_LIST[0].id);
  const [propertyType, setPropertyType] = useState(initialSettings?.propertyType || 'Apartment');
  const [bedrooms, setBedrooms] = useState('2');
  const [visitType, setVisitType] = useState('One-time visit');
  const [focus, setFocus] = useState([]);
  const toggleFocus = (value) => setFocus((items) => items.includes(value) ? items.filter((item) => item !== value) : [...items, value]);
  const chosenService = SERVICES_LIST.find((item) => item.id === serviceType) || SERVICES_LIST[0];
  const openBooking = () => onOpenBooking({ serviceType: chosenService.id, notes: `Property: ${propertyType}; bedrooms: ${bedrooms}; visit: ${visitType}; priorities: ${focus.join(', ') || 'to discuss'}` });
  const focusOptions = ['Kitchen', 'Bathrooms', 'Bedrooms', 'Living area', 'Furniture'];

  return <div id="calculator" className="grid gap-6 lg:grid-cols-[1.35fr_.65fr]">
    <div className="space-y-6 rounded-3xl border border-slate-200 bg-white p-5 shadow-sm sm:p-8">
      <div><span className="text-xs font-bold uppercase tracking-[.16em] text-[#23834e]">Build your enquiry</span><h2 className="mt-2 font-serif text-2xl font-bold text-[#14271d] sm:text-3xl">Tell us what you need cleaned</h2><p className="mt-2 text-sm leading-6 text-slate-600">Use these details to help the team understand your request. A price is confirmed after the scope is reviewed.</p></div>
      <div><label htmlFor="quote-service" className="mb-2 block text-xs font-extrabold text-slate-700">Cleaning service</label><select id="quote-service" value={serviceType} onChange={(event) => setServiceType(event.target.value)} className="w-full rounded-xl border border-slate-200 bg-slate-50 px-4 py-3 text-sm text-slate-900 outline-none focus:border-emerald-600 focus:bg-white">{SERVICES_LIST.map((service) => <option key={service.id} value={service.id}>{service.title}</option>)}</select></div>
      <div><p className="mb-2 text-xs font-extrabold text-slate-700">Property type</p><div className="grid grid-cols-2 gap-3">{['Apartment', 'Villa'].map((type) => <button key={type} type="button" onClick={() => setPropertyType(type)} className={`flex min-h-12 items-center justify-center gap-2 rounded-xl border px-4 py-3 text-sm font-bold transition ${propertyType === type ? 'border-[#23834e] bg-[#edf6ef] text-[#17613d]' : 'border-slate-200 bg-white text-slate-600 hover:border-emerald-300'}`}><Home className="h-4 w-4" />{type}</button>)}</div></div>
      <div className="grid gap-4 sm:grid-cols-2"><label className="block text-xs font-extrabold text-slate-700">Bedrooms or rooms<select value={bedrooms} onChange={(event) => setBedrooms(event.target.value)} className="mt-2 w-full rounded-xl border border-slate-200 bg-slate-50 px-4 py-3 text-sm font-normal text-slate-900 outline-none focus:border-emerald-600 focus:bg-white">{['Studio','1','2','3','4','5','6+'].map((value) => <option key={value} value={value}>{value === 'Studio' ? 'Studio' : `${value} ${value === '1' ? 'bedroom' : 'bedrooms'}`}</option>)}</select></label><label className="block text-xs font-extrabold text-slate-700">Visit type<select value={visitType} onChange={(event) => setVisitType(event.target.value)} className="mt-2 w-full rounded-xl border border-slate-200 bg-slate-50 px-4 py-3 text-sm font-normal text-slate-900 outline-none focus:border-emerald-600 focus:bg-white"><option>One-time visit</option><option>Recurring visits</option><option>Holiday home turnover</option></select></label></div>
      <fieldset><legend className="mb-2 text-xs font-extrabold text-slate-700">Areas to prioritize <span className="font-normal text-slate-500">(optional)</span></legend><div className="flex flex-wrap gap-2">{focusOptions.map((item) => <button key={item} type="button" aria-pressed={focus.includes(item)} onClick={() => toggleFocus(item)} className={`inline-flex items-center gap-1.5 rounded-full border px-3 py-2 text-xs font-semibold transition ${focus.includes(item) ? 'border-emerald-300 bg-[#edf6ef] text-[#17613d]' : 'border-slate-200 bg-white text-slate-600 hover:border-emerald-200'}`}>{focus.includes(item) && <Check className="h-3.5 w-3.5" />}{item}</button>)}</div></fieldset>
    </div>
    <aside className="flex flex-col justify-between rounded-3xl bg-[#174b32] p-6 text-white sm:p-8"><div><span className="flex h-11 w-11 items-center justify-center rounded-xl bg-white/10 text-emerald-100"><CalendarDays className="h-5 w-5" /></span><p className="mt-6 text-xs font-bold uppercase tracking-[.16em] text-emerald-200">Your enquiry</p><h2 className="mt-2 font-serif text-2xl font-bold">{chosenService.title}</h2><p className="mt-3 text-sm leading-6 text-white/75">{propertyType} · {bedrooms === 'Studio' ? 'Studio' : `${bedrooms} bedroom${bedrooms === '1' ? '' : 's'}`} · {visitType}</p><div className="mt-5 border-t border-white/15 pt-5"><p className="text-sm font-bold">Quote confirmed with the team</p><p className="mt-2 text-xs leading-5 text-white/70">Price and availability depend on the confirmed service scope and property details.</p></div></div><button type="button" onClick={openBooking} className="mt-8 inline-flex min-h-12 items-center justify-center gap-2 rounded-xl bg-white px-5 py-3 text-sm font-extrabold text-[#174b32] transition hover:bg-emerald-50">Request a quote <ArrowRight className="h-4 w-4" /></button><p className="mt-3 flex items-center justify-center gap-1.5 text-[11px] text-white/65"><MessageSquare className="h-3.5 w-3.5" />No payment is taken here.</p></aside>
  </div>;
}
