import React from 'react';
import { Link } from 'react-router-dom';
import { ArrowRight } from 'lucide-react';
import { SERVICES_LIST } from '../data/cleaningData';
import { servicePathFor } from '../data/servicePages';

export default function ServicesSection({ onOpenBooking }) {
  return <section className="py-14 sm:py-20"><div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><div className="mb-8 flex items-end justify-between gap-4"><div><span className="text-xs font-bold uppercase tracking-[.16em] text-emerald-700">Golden Home services</span><h2 className="mt-2 font-serif text-3xl font-bold text-slate-900">Cleaning options for your home</h2></div><Link to="/services" className="inline-flex items-center gap-2 text-sm font-bold text-emerald-800">All services <ArrowRight className="h-4 w-4" /></Link></div><div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{SERVICES_LIST.map((service) => <article key={service.id} className="overflow-hidden rounded-2xl border border-emerald-100 bg-white shadow-sm"><img src={service.image} alt={service.title} loading="lazy" className="h-48 w-full object-cover" /><div className="p-5"><p className="text-xs font-bold text-emerald-700">{service.tag}</p><h3 className="mt-1 font-serif text-xl font-bold text-slate-900">{service.title}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{service.description}</p><div className="mt-4 flex gap-2"><Link to={servicePathFor(service.id)} className="flex-1 rounded-xl border border-emerald-200 px-3 py-2.5 text-center text-xs font-bold text-emerald-800">Service details</Link><button onClick={() => onOpenBooking({ serviceType: service.id })} className="flex-1 rounded-xl bg-[#174b32] px-3 py-2.5 text-xs font-bold text-white">Ask about it</button></div></div></article>)}</div></div></section>;
}
